### ISSUE TITLE
REACT

### ISSUE THREAD

**Issue by gabrielaortiz6** [CJB14/Robo-art#12]

**Comment by NIIODARTEY010** [comment]
+-- https://github.com/chalk/chalk?sponsor=1
| | `-- chalk@4.1.2
| `-- https://github.com/chalk/ansi-styles?sponsor=1
|     `-- ansi-styles@4.3.0
+-- https://github.com/sponsors/ljharb
|   `-- minimist@1.2.8
`-- https://github.com/sponsors/isaacs
    `-- glob@7.2.3, rimraf@3.0.2

**Comment by NIIODARTEY010** [comment]
How can I install this for me to start creating my react app easily
